import type { AuditAction } from '@prisma/client';

/** 監査ログのアクション種別 → 日本語ラベル */
export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  USER_LOGIN: 'ログイン',
  USER_LOGIN_FAILED: 'ログイン失敗',
  USER_LOGOUT: 'ログアウト',
  USER_CREATE: 'ユーザー追加',
  USER_UPDATE: 'ユーザー更新',
  USER_DELETE: 'ユーザー削除',
  USER_PASSWORD_CHANGE: 'パスワード変更',
  USER_TERMS_ACCEPT: '利用規約同意',
  GROUP_CREATE: 'グループ作成',
  GROUP_UPDATE: 'グループ更新',
  GROUP_DELETE: 'グループ削除',
  GROUP_SYNC_MEMBERS: 'グループメンバー同期',
  GROUP_ADD_MEMBER: 'グループメンバー追加',
  GROUP_END_MEMBERSHIP: 'グループメンバー終了',
  GROUP_REMOVE_MEMBERSHIP: 'グループメンバー削除',
  SALES_RECORD_CREATE: '売上データ入力',
  SALES_RECORD_UPDATE: '売上データ更新',
  SALES_RECORD_DELETE: '売上データ削除',
  TARGET_UPSERT: '目標設定',
  TARGET_BULK_UPSERT: '目標一括設定',
  GROUP_TARGET_UPSERT: 'グループ目標設定',
  SETTINGS_UPDATE: 'システム設定変更',
  INTEGRATION_STATUS_UPDATE: '連携ステータス変更',
  DISPLAY_CONFIG_UPDATE: 'ディスプレイ設定変更',
  CUSTOM_FIELD_CREATE: 'カスタムフィールド追加',
  CUSTOM_FIELD_UPDATE: 'カスタムフィールド更新',
  CUSTOM_FIELD_DELETE: 'カスタムフィールド削除',
  CUSTOM_SLIDE_CREATE: 'カスタムスライド追加',
  CUSTOM_SLIDE_UPDATE: 'カスタムスライド更新',
  CUSTOM_SLIDE_DELETE: 'カスタムスライド削除',
  TENANT_CREATE: 'テナント作成',
  TENANT_UPDATE: 'テナント更新',
  TENANT_DELETE: 'テナント削除',
  DATA_TYPE_CREATE: 'データ種類追加',
  DATA_TYPE_UPDATE: 'データ種類更新',
  DATA_TYPE_DELETE: 'データ種類削除',
  SUBSCRIPTION_CREATE: 'サブスクリプション作成',
  SUBSCRIPTION_UPDATE: 'サブスクリプション更新',
  SUBSCRIPTION_EXPIRE: 'サブスクリプション失効',
};
